[package]
name = "contentometre"
version = "0.1.0"
authors = ["Ian FRASER <ian.fraser@decathlon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
